
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytqenpdwynascsmfolbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cWVucGR3eW5hc2NzbWZvbGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTE5MTIsImV4cCI6MjA2MzA2NzkxMn0.AyuwhetMHyarGSRKkuG-uIFwNE850WDgSm8WV22VW0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add custom type for reports until Supabase types are updated
export type ReportType = {
  id: string;
  type: 'water' | 'component';
  name: string;
  month: string;
  year: string; // Changed from number to string to match database schema
  created_at: string;
  file_url?: string;
  status: 'pending' | 'completed' | 'failed';
  data?: any;
}
