name: Supabase Migrations

on:
  workflow_dispatch:
  push:
    paths:
      - 'supabase/migrations/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Verify DB URL secret
        run: |
          if [ -z "${SUPABASE_DB_URL}" ]; then
            echo "SUPABASE_DB_URL is not set. Add it in GitHub > Settings > Secrets and variables > Actions." >&2
            exit 1
          fi

      - name: Apply migrations in order
        run: |
          set -e
          for f in $(ls -1 supabase/migrations/*.sql | sort); do
            echo "Applying $f"
            PGPASSWORD= dummy psql "${SUPABASE_DB_URL}" -v ON_ERROR_STOP=1 -f "$f"
          done

  seed-minimal:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: apply
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Seed baseline sources and aliases
        run: |
          set -e
          PGPASSWORD= dummy psql "${SUPABASE_DB_URL}" -v ON_ERROR_STOP=1 -f supabase/migrations/20250831153000_seed_minimal.sql || true
